/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * 
 * @generated
 */
package com.airbnb.reair.incremental.thrift;


public enum TReplicationOperation implements org.apache.thrift.TEnum {
  COPY_UNPARTITIONED_TABLE(0), COPY_PARTITIONED_TABLE(1), COPY_PARTITION(2), COPY_PARTITIONS(
      3), DROP_TABLE(4), DROP_PARTITION(5), RENAME_TABLE(6), RENAME_PARTITION(7);

  private final int value;

  private TReplicationOperation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * 
   * @return null if the value is not found.
   */
  public static TReplicationOperation findByValue(int value) {
    switch (value) {
      case 0:
        return COPY_UNPARTITIONED_TABLE;
      case 1:
        return COPY_PARTITIONED_TABLE;
      case 2:
        return COPY_PARTITION;
      case 3:
        return COPY_PARTITIONS;
      case 4:
        return DROP_TABLE;
      case 5:
        return DROP_PARTITION;
      case 6:
        return RENAME_TABLE;
      case 7:
        return RENAME_PARTITION;
      default:
        return null;
    }
  }
}
